---
- name: debian | Installing Pre-Reqs
  apt:
    name:
      - apt-transport-https
      - gnupg
      - libpcap0.8
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Copying Elasticsearch GPG Key
  copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch

- name: debian | Adding Elasticsearch GPG Key
  apt_key:
    file: /tmp/GPG-KEY-elasticsearch
    state: present
  become: true

- name: debian | adding packetbeat repo
  apt_repository:
    repo: "{{ 'deb '+es_packetbeat_repo_url+'/'+es_packetbeat_major_ver+'/apt stable main' }}"
    state: present
  become: true

- name: debian | Installing packetbeat {{ es_packetbeat_minor_version }}
  apt:
    name: "{{ 'packetbeat='+es_packetbeat_minor_version|string }}"
    state: present
  become: true
  register: result
  until: result is successful
