---
- name: debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - apt-transport-https
    - libpcap0.8

# Adding Elastic Repo Key
- name: debian | Adding Elasticsearch Repo Key
  apt_key:
    url: "{{ es_packetbeat_repo_key }}"
    state: present
  become: true

# Adding Packetbeat Repo
- name: debian | Adding Packetbeat Repo
  apt_repository:
    repo: "deb {{ es_packetbeat_repo_url }}/packages/{{ es_packetbeat['major_version'] }}/apt stable main"
    state: present
  become: true

# Installing Packetbeat version defined by es_packetbeat['minor_version']
- name: debian | Installing Packetbeat {{ es_packetbeat['minor_version'] }}
  apt:
    name: "packetbeat={{ es_packetbeat['minor_version'] }}"
    state: present
  become: true
