---
- name: redhat | Installing Pre-Reqs
  package:
    name:
      - libpcap
    state: present
  become: true

- name: redhat | Copying Elasticsearch GPG Key
  copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch

- name: redhat | Adding Elasticsearch GPG Key
  rpm_key:
    key: /tmp/GPG-KEY-elasticsearch
    state: present
  become: true

- name: redhat | Adding packetbeat Repo
  yum_repository:
    baseurl: "{{ es_packetbeat_repo_url+'/'+es_packetbeat_major_ver+'/yum' }}"
    description: "packetbeat repository for {{ es_packetbeat_major_ver }} packages"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ es_packetbeat_repo_key }}"
    name: "{{ 'packetbeat-'+es_packetbeat_major_ver }}"
    state: present
  become: true

- name: redhat | Installing packetbeat
  package:
    name: "{{ 'packetbeat-'+es_packetbeat_minor_version|string }}"
    state: present
  become: true
  register: result
  until: result is successful
